fstab: improved password detection and fixed parsing error
E.g. mount.cifs can use pass= instead of password= and
cred= can alternatively be used to specify a credential file.

Continue on empty lines because the line.split() call resulted in
ValueError: not enough values to unpack (expected 6, got 0)